### ISSUE TITLE
The code will not use the GPU...and only uses one CPU thread

### ISSUE THREAD

**Issue by pusj** [pusj/LSTM-Time-Series-Analysis-using-Tensorflow#2]
Can Scikit and/or Sklearn in some obscure way be behind this?

**Comment by surjithbs17** [comment]
A good option may be just run the estimator as a tensorflow session in gpu. In that case you would have to write your own fit function. With activation functions and SGD.

**Comment by pusj** [comment]
@surjithbs17 

This sounds like a great suggestion, could you please include code with this suggestion? 

Also, do you have any suggestions of how to parallelize this computation using the CPU a bit more efficiently? As I mentioned, only one thread is used now...and I have a few more at my disposal. There is an excellent way to increase the number of computational nodes (n_jobs) for a linear regression model using scikit (http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html), I was wondering if there exists a similar approach for fitting (training) of the estimator is our code. 

Best Regards
Staffan

**Comment by surjithbs17** [comment]
@pusj 

I would suggest you to have a looh at this link https://www.tensorflow.org/tutorials/using_gpu

You can set affinity to a processor/gpu using tf.device command.

```python
# Creates a graph.
with tf.device('/gpu:2'):
  a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
  b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
  c = tf.matmul(a, b)
# Creates a session with log_device_placement set to True.
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
# Runs the op.
print sess.run(c)
```

In our case we can try something like

```python
with tf.device('/gpu:0'):
    c = regressor.fit(X['train'], y['train'],
              monitors=[validation_monitor],
              batch_size=BATCH_SIZE,
              steps=TRAINING_STEPS)
# Creates a session with log_device_placement set to True.
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
# Runs the op.
sess.run(c)
```

**Comment by surjithbs17** [comment]
@pusj I am not sure whether that will work. But that is how we have to run the model in GPU .

**Comment by pusj** [comment]
@surjithbs17 

Thank you for this, good suggestions! I will try out your suggested code within a few short days.

**Comment by pusj** [comment]
@surjithbs17 ,

No need for creating sess object, the code is using the GPU....funny that I didn't see this before, maybe something else has changed (numpy tensors being treated differently perhaps).

The code works fine, I have good control of what data goes in and out to the net. What I am working now with is to better follow the creation of the net; number och nodes and layers, type of activation function, how DNN couples with the RNN etc. After this I'm probably going to write some simple LSTM time series predictor from scratch (this code contains too many shortcuts for my liking), I might make use of certain parts of the code, such as the data generation. 

Have you come across any other LSTM (example) codes that are worth looking into?

BR
Staffan

**Comment by pusj** [comment]
@surjithbs17 

It took me a few hours to add some noise...but it was worth it; I've added equal amount of np.random.normal to 'train', 'val' and 'test' and the result looks better than I expected. There was no need for tuning the hyperparameters when adding the noise. I spent a few minutes tuning the hyperparameters before adding the noise and this setup worked fine also with noise added. 

![noise_added](https://cloud.githubusercontent.com/assets/26404839/26523926/1a1b7d7a-4324-11e7-88bd-5807f2220897.png)

BR
Staffan

**Comment by surjithbs17** [comment]
@pusj I haven't found anything better than what you have. BTW, I achieved the task I had to do with the model we have and just modified the hyperparameters. The results look great. 

You are saying that numpy tensors always run in gpus if there is a gpu support?

Best,
Surjith

**Comment by pusj** [comment]
@surjithbs17 ,

Thank you for this acknowledgment, kind of you. 

I agree that hyperparameter tuning is needed for all "new" data sets, from the original model I have optimized quite a few hyperparameters to get a accurate prediction response for the sinusoidal model. 

I don't really see this but do you which part of the code controls the number of layers, can you see where this is defined? The number of neurons is easy to see but the number of layers is more difficult. Also, does the number of neurons that is defined in the input valid as the amount of neurons for all hidden layers (given that there is > 1 hidden layer)?

Your question if all numpy arrays/tensors are evaluated using the GPU...Yes, this seems to be the case when a tensorflow training procedure is used.

Best Regards
Staffan

**Comment by pusj** [comment]
This thread was originally for determine how to get the GPU working with this code. This works fine now, I'm guessing that I did not install TF correctly at the time when this thread was created....
