### ISSUE TITLE
Multiple input data on this model throws out an error

### ISSUE THREAD

**Issue by surjithbs17** [pusj/LSTM-Time-Series-Analysis-using-Tensorflow#4]
When I tried your reference for giving multiple inputs (2 variables), and one output for prediction. I get an issue of lhs not matching rhs. Somewhere deep inside the abstraction of tensorflow.

I modified the code in load_predictor.py. for loading my csv file. I have attached the screen log in the attachments. I dont see any issue in my data, each data individually works well for the model, when I add them in the dataframe, throws out a nasty error. I have attached the screenlog below. 

Any idea what I should do to feed multidimensional input data.

[log.txt](https://github.com/pusj/LSTM-Time-Series-Analysis-using-Tensorflow/files/889115/log.txt)

Attached the files I am working with.
[LSTM-Time-Series-Analysis-using-Tensorflow.zip](https://github.com/pusj/LSTM-Time-Series-Analysis-using-Tensorflow/files/889117/LSTM-Time-Series-Analysis-using-Tensorflow.zip)

**Comment by pusj** [comment]
@surjithbs17 ,

Could we please work with issues #1 and #2 before we increase the complexity? The aim of this repository is to fully understand the sine predictor. 

https://s-media-cache-ak0.pinimg.com/736x/aa/4f/87/aa4f87c10b231b2e0a8b68210c7978cc.jpg

Best Regards
Staffan

**Comment by surjithbs17** [comment]
Yea. Sure. @pusj . 

Thanks,
Surjith

**Comment by surjithbs17** [comment]
@punj Looks like I just solved the bug. Clear resources folder(log) before running the code.

That solved the issue.

**Comment by pusj** [comment]
I also noticed this when I was trying the code out...I tried to see the effects of using different amount of layers...but this would not run unless I removed the log files...
